## FT084 - Introdução a Mineração de Dados
---
### Tarefa 03: Multilayer Perceptrons (MLP)

Este código tem por objetivo a resolução da tarefa em questão, que consiste na implementação de redes neurais do tipo MLP.  
Instruções para o experimento:
1. Utilize a mesma metodologia da atividade anterior, ou seja, subamostragem aleatória com 5 repetições, sendo 70% dos dados para treinamento e 30% dos dados para teste (em cada repetição);
2. Faça todos os ajustes necessários no conjunto de dados para que as MLPs possam ser aplicadas (e descreva, no relatório, os ajustes feitos);
3. Apresente o erro médio de classificação, para o conjunto de testes, e compare os resultados com os obtidos na atividade anterior;
4. Apresente claramente a metodologia adotada, os classificadores utilizados (versões e parâmetros) e discuta os resultados obtidos.
---

#### 1) Importação das bibliotecas  
Serão utilizados alguns pacotes para a implementação do código. São eles:
- pandas: leitura dos arquivos
- numpy, scipy: cálculo de algumas estatísticas
- sklearn: separação dos dados entre treino e teste, transformação dos atributos categóricos para numéricos (caso necessário), matriz de confusão e avaliação do erro
- keras: algoritmo de classificação

In [1]:
# Importação das Bibliotecas
import pandas as pd
import numpy as np
from scipy import stats
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils

Using TensorFlow backend.

#### 2) Criação do dataset
Será gerado um objeto do tipo dataframe com a base de dados bupa.data, utilizando os nomes dos atributos disposíveis em bupa.names.

In [2]:
# Nomes das colunas
columns_names = [
    'mcv',
    'alkphos',
    'sgpt',
    'sgot',
    'gammagt',
    'drinks',
    'selector'
]

# Criação do dataset
dataset = pd.read_table("bupa.data", sep = ",", header = None, names = columns_names)
dataset

     mcv  alkphos  sgpt  sgot  gammagt  drinks  selector
0     85       92    45    27       31     0.0         1
1     85       64    59    32       23     0.0         2
2     86       54    33    16       54     0.0         2
3     91       78    34    24       36     0.0         2
4     87       70    12    28       10     0.0         2
..   ...      ...   ...   ...      ...     ...       ...
340   99       75    26    24       41    12.0         1
341   96       69    53    43      203    12.0         2
342   98       77    55    35       89    15.0         1
343   91       68    27    26       14    16.0         1
344   98       99    57    45       65    20.0         1

[345 rows x 7 columns]

#### 3) Análise da base de dados
Analisar o tipo dos dados da base (numéricos ou categóricos), se há valores faltantes, e se é necessário realizar alguma transformação prévia.

In [3]:
# Observando o tamanho da base de dados
dataset.shape

(345, 7)

In [4]:
# Utilizando o método describe() para analisar a base de dados e validar se todos os atributos são numéricos
dataset.describe()

,mcv,alkphos,sgpt,sgot,gammagt,drinks,selector
count,345.000000,345.000000,345.000000,345.000000,345.000000,345.000000,345.000000
mean,90.159420,69.869565,30.405797,24.643478,38.284058,3.455072,1.579710
std,4.448096,18.347670,19.512309,10.064494,39.254616,3.337835,0.494322
min,65.000000,23.000000,4.000000,5.000000,5.000000,0.000000,1.000000
25%,87.000000,57.000000,19.000000,19.000000,15.000000,0.500000,1.000000
50%,90.000000,67.000000,26.000000,23.000000,25.000000,3.000000,2.000000
75%,93.000000,80.000000,34.000000,27.000000,46.000000,6.000000,2.000000
max,103.000000,138.000000,155.000000,82.000000,297.000000,20.000000,2.000000

In [5]:
# Criando um vetor para verificar se há valores nulos
null_array = [dataset.iloc[:, i].isnull().unique() for i in range(7)]
null_array

[array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False])]

In [6]:
# Criando um vetor para verificar se há valores faltantes
na_array = [dataset.iloc[:, i].isna().unique() for i in range(7)]
na_array

[array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False]),
 array([False])]

#### 4) Transformação da base de dados
Classificar a coluna "drinks" de acordo com as informações do arquivo bupa.names, além de analisar a coluna "selector", avaliando se pode ser usada como divisor dos dados.
- "drinks" 3 5 pode ser considerado um tipo de seleção na base de dados (de acordo com esse artigo: McDermott & Forsyth 2016, Diagnosing a disorder in a classification benchmark, Pattern Recognition Letters, Volume 73.)
- "selector" divide a base de dados em uma determina proporção; será avaliada essa proporção, e se ela é satisfatória

In [7]:
# Classificando a coluna "drinks"
dataset.loc[dataset['drinks'] <= 6, 'drinks'] = 0
dataset.loc[dataset['drinks'] > 6, 'drinks'] = 1
dataset

     mcv  alkphos  sgpt  sgot  gammagt  drinks  selector
0     85       92    45    27       31     0.0         1
1     85       64    59    32       23     0.0         2
2     86       54    33    16       54     0.0         2
3     91       78    34    24       36     0.0         2
4     87       70    12    28       10     0.0         2
..   ...      ...   ...   ...      ...     ...       ...
340   99       75    26    24       41     1.0         1
341   96       69    53    43      203     1.0         2
342   98       77    55    35       89     1.0         1
343   91       68    27    26       14     1.0         1
344   98       99    57    45       65     1.0         1

[345 rows x 7 columns]

In [8]:
# Como a proporção é diferente de 30% e 70%, a coluna "selector" será descartada do dataset.
dataset.drop(columns = 'selector', inplace = True)
columns_names.pop(-1)
dataset

     mcv  alkphos  sgpt  sgot  gammagt  drinks
0     85       92    45    27       31     0.0
1     85       64    59    32       23     0.0
2     86       54    33    16       54     0.0
3     91       78    34    24       36     0.0
4     87       70    12    28       10     0.0
..   ...      ...   ...   ...      ...     ...
340   99       75    26    24       41     1.0
341   96       69    53    43      203     1.0
342   98       77    55    35       89     1.0
343   91       68    27    26       14     1.0
344   98       99    57    45       65     1.0

[345 rows x 6 columns]

#### 5) Normalização dos Dados
Procedimento realizado antes de iniciar a construção do modelo, a fim de todos os valores estarem na mesma escala.

In [9]:
numpy_array = dataset.values
min_max_scaler = preprocessing.MinMaxScaler()
new_dataset = min_max_scaler.fit_transform(numpy_array)
dataset = pd.DataFrame(new_dataset, columns = columns_names)
dataset

          mcv   alkphos      sgpt      sgot   gammagt  drinks
0    0.526316  0.600000  0.271523  0.285714  0.089041     0.0
1    0.526316  0.356522  0.364238  0.350649  0.061644     0.0
2    0.552632  0.269565  0.192053  0.142857  0.167808     0.0
3    0.684211  0.478261  0.198675  0.246753  0.106164     0.0
4    0.578947  0.408696  0.052980  0.298701  0.017123     0.0
..        ...       ...       ...       ...       ...     ...
340  0.894737  0.452174  0.145695  0.246753  0.123288     1.0
341  0.815789  0.400000  0.324503  0.493506  0.678082     1.0
342  0.868421  0.469565  0.337748  0.389610  0.287671     1.0
343  0.684211  0.391304  0.152318  0.272727  0.030822     1.0
344  0.868421  0.660870  0.350993  0.519481  0.205479     1.0

[345 rows x 6 columns]

#### 6) Divisão entre Classe e Atributos
Definir dentro do dataset qual é a variável que será classificada, e quais são as variáveis preditoras.

In [10]:
# Definição das Classes
classes = dataset['drinks']

# Definição dos atributos
attributes_names = [
    'mcv',
    'alkphos',
    'sgpt',
    'sgot',
    'gammagt'
]

attributes = dataset[attributes_names]

# Transformação da classe para o formato "dummy", pois temos uma rede neural com 3 neurônios na camada de saída
class_dummy = np_utils.to_categorical(classes)

#### 7) Criação do Modelo
Criaçao de uma função que irá encapsular o processo de criação da rede neural, retornando a classe prevista para cada instância e o erro de classificação do algoritmo.

In [11]:
def mlp():
    # Divisão da base de dados entre treinamento e teste.
    x_train, x_test, y_train, y_test = train_test_split(attributes, class_dummy, test_size = 0.3, random_state = 0)
    
    # Criação da estrutura da rede neural com a classe Sequential (sequência de camadas)
    modelo = Sequential()
    modelo.add(Dense(units = 100, input_dim = 5))
    # modelo.add(Dense(units = 50))
    modelo.add(Dense(units = 2, activation = 'softmax'))
    
    # Visualização da estrutura da rede neural
    # modelo.summary()
    
    # Configuração dos parâmetros da rede neural (adam = algoritmo para atualizar os pesos e loss = cálculo do erro)
    modelo.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
    
    # Treinamento, dividindo a base de treinamento em uma porção para validação (validation_data)
    modelo.fit(x_train, y_train, epochs = 100, validation_data = (x_test, y_test))
    
    # Previsões
    previsoes = modelo.predict(x_test)
    previsoes = (previsoes > 0.5)
    previsoes_final = [0 if i[0] == True else 1 for i in previsoes]
    
    # Precisão e Erro
    y_test_final = [0 if i[0] == 1 else 1 for i in y_test]
    precisao = accuracy_score(y_test_final, previsoes_final)
    precisao
    erro = 1 - precisao
    
    
    return erro

In [12]:
mlp()

Train on 241 samples, validate on 104 samples
Epoch 1/100
241/241 [==============================] - 0s 306us/step - loss: 0.6963 - accuracy: 0.4813 - val_loss: 0.5938 - val_accuracy: 0.9038
Epoch 2/100
241/241 [==============================] - 0s 29us/step - loss: 0.5638 - accuracy: 0.8423 - val_loss: 0.4796 - val_accuracy: 0.9038
Epoch 3/100
241/241 [==============================] - 0s 29us/step - loss: 0.5018 - accuracy: 0.8423 - val_loss: 0.4124 - val_accuracy: 0.9038
Epoch 4/100
241/241 [==============================] - 0s 25us/step - loss: 0.4698 - accuracy: 0.8423 - val_loss: 0.3823 - val_accuracy: 0.9038
Epoch 5/100
241/241 [==============================] - 0s 29us/step - loss: 0.4610 - accuracy: 0.8423 - val_loss: 0.3695 - val_accuracy: 0.9038
Epoch 6/100
241/241 [==============================] - 0s 25us/step - loss: 0.4571 - accuracy: 0.8423 - val_loss: 0.3645 - val_accuracy: 0.9038
Epoch 7/100
241/241 [==============================] - 0s 25us/step - loss: 0.4543 - accuracy: 0.8423 - val_loss: 0.3633 - val_accuracy: 0.9038
Epoch 8/100
241/241 [==============================] - 0s 25us/step - loss: 0.4511 - accuracy: 0.8423 - val_loss: 0.3628 - val_accuracy: 0.9038
Epoch 9/100
241/241 [==============================] - 0s 25us/step - loss: 0.4486 - accuracy: 0.8423 - val_loss: 0.3644 - val_accuracy: 0.9038
Epoch 10/100
241/241 [==============================] - 0s 25us/step - loss: 0.4442 - accuracy: 0.8423 - val_loss: 0.3632 - val_accuracy: 0.9038
Epoch 11/100
241/241 [==============================] - 0s 25us/step - loss: 0.4415 - accuracy: 0.8423 - val_loss: 0.3612 - val_accuracy: 0.9038
Epoch 12/100
241/241 [==============================] - 0s 33us/step - loss: 0.4393 - accuracy: 0.8423 - val_loss: 0.3601 - val_accuracy: 0.9038
Epoch 13/100
241/241 [==============================] - 0s 29us/step - loss: 0.4359 - accuracy: 0.8423 - val_loss: 0.3569 - val_accuracy: 0.9038
Epoch 14/100
241/241 [==============================] - 0s 29us/step - loss: 0.4340 - accuracy: 0.8423 - val_loss: 0.3576 - val_accuracy: 0.9038
Epoch 15/100
241/241 [==============================] - 0s 29us/step - loss: 0.4311 - accuracy: 0.8423 - val_loss: 0.3546 - val_accuracy: 0.9038
Epoch 16/100
241/241 [==============================] - 0s 25us/step - loss: 0.4289 - accuracy: 0.8423 - val_loss: 0.3559 - val_accuracy: 0.9038
Epoch 17/100
241/241 [==============================] - 0s 25us/step - loss: 0.4262 - accuracy: 0.8423 - val_loss: 0.3533 - val_accuracy: 0.9038
Epoch 18/100
241/241 [==============================] - 0s 25us/step - loss: 0.4238 - accuracy: 0.8423 - val_loss: 0.3526 - val_accuracy: 0.9038
Epoch 19/100
241/241 [==============================] - 0s 25us/step - loss: 0.4224 - accuracy: 0.8423 - val_loss: 0.3483 - val_accuracy: 0.9038
Epoch 20/100
241/241 [==============================] - 0s 25us/step - loss: 0.4199 - accuracy: 0.8382 - val_loss: 0.3511 - val_accuracy: 0.9038
Epoch 21/100
241/241 [==============================] - 0s 25us/step - loss: 0.4174 - accuracy: 0.8382 - val_loss: 0.3487 - val_accuracy: 0.9038
Epoch 22/100
241/241 [==============================] - 0s 25us/step - loss: 0.4155 - accuracy: 0.8382 - val_loss: 0.3457 - val_accuracy: 0.9038
Epoch 23/100
241/241 [==============================] - 0s 25us/step - loss: 0.4143 - accuracy: 0.8382 - val_loss: 0.3441 - val_accuracy: 0.9038
Epoch 24/100
241/241 [==============================] - 0s 25us/step - loss: 0.4122 - accuracy: 0.8382 - val_loss: 0.3454 - val_accuracy: 0.9038
Epoch 25/100
241/241 [==============================] - 0s 25us/step - loss: 0.4106 - accuracy: 0.8382 - val_loss: 0.3470 - val_accuracy: 0.8942
Epoch 26/100
241/241 [==============================] - 0s 25us/step - loss: 0.4107 - accuracy: 0.8382 - val_loss: 0.3509 - val_accuracy: 0.8942
Epoch 27/100
241/241 [==============================] - 0s 25us/step - loss: 0.4094 - accuracy: 0.8340 - val_loss: 0.3490 - val_accuracy: 0.8942
Epoch 28/100
241/241 [==============================] - 0s 21us/step - loss: 0.4088 - accuracy: 0.8340 - val_loss: 0.3405 - val_accuracy: 0.8942
Epoch 29/100
241/241 [==============================] - 0s 25us/step - loss: 0.4065 - accuracy: 0.8382 - val_loss: 0.3428 - val_accuracy: 0.8942
Epoch 30/100
241/241 [==============================] - 0s 25us/step - loss: 0.4051 - accuracy: 0.8423 - val_loss: 0.3433 - val_accuracy: 0.8942
Epoch 31/100
241/241 [==============================] - 0s 29us/step - loss: 0.4037 - accuracy: 0.8465 - val_loss: 0.3448 - val_accuracy: 0.8846
Epoch 32/100
241/241 [==============================] - 0s 25us/step - loss: 0.4034 - accuracy: 0.8506 - val_loss: 0.3473 - val_accuracy: 0.8846
Epoch 33/100
241/241 [==============================] - 0s 25us/step - loss: 0.4027 - accuracy: 0.8506 - val_loss: 0.3475 - val_accuracy: 0.8846
Epoch 34/100
241/241 [==============================] - 0s 25us/step - loss: 0.4015 - accuracy: 0.8506 - val_loss: 0.3461 - val_accuracy: 0.8846
Epoch 35/100
241/241 [==============================] - 0s 25us/step - loss: 0.4009 - accuracy: 0.8506 - val_loss: 0.3424 - val_accuracy: 0.8846
Epoch 36/100
241/241 [==============================] - 0s 25us/step - loss: 0.4007 - accuracy: 0.8506 - val_loss: 0.3405 - val_accuracy: 0.8846
Epoch 37/100
241/241 [==============================] - 0s 25us/step - loss: 0.4000 - accuracy: 0.8506 - val_loss: 0.3416 - val_accuracy: 0.8846
Epoch 38/100
241/241 [==============================] - 0s 21us/step - loss: 0.3989 - accuracy: 0.8506 - val_loss: 0.3480 - val_accuracy: 0.8846
Epoch 39/100
241/241 [==============================] - 0s 25us/step - loss: 0.3987 - accuracy: 0.8465 - val_loss: 0.3482 - val_accuracy: 0.8846
Epoch 40/100
241/241 [==============================] - 0s 25us/step - loss: 0.3984 - accuracy: 0.8465 - val_loss: 0.3499 - val_accuracy: 0.8846
Epoch 41/100
241/241 [==============================] - 0s 29us/step - loss: 0.3986 - accuracy: 0.8423 - val_loss: 0.3509 - val_accuracy: 0.8846
Epoch 42/100
241/241 [==============================] - 0s 29us/step - loss: 0.3971 - accuracy: 0.8465 - val_loss: 0.3443 - val_accuracy: 0.8846
Epoch 43/100
241/241 [==============================] - 0s 25us/step - loss: 0.3968 - accuracy: 0.8465 - val_loss: 0.3434 - val_accuracy: 0.8846
Epoch 44/100
241/241 [==============================] - 0s 25us/step - loss: 0.3965 - accuracy: 0.8465 - val_loss: 0.3450 - val_accuracy: 0.8846
Epoch 45/100
241/241 [==============================] - 0s 25us/step - loss: 0.3959 - accuracy: 0.8465 - val_loss: 0.3426 - val_accuracy: 0.8846
Epoch 46/100
241/241 [==============================] - 0s 25us/step - loss: 0.3962 - accuracy: 0.8465 - val_loss: 0.3447 - val_accuracy: 0.8846
Epoch 47/100
241/241 [==============================] - 0s 25us/step - loss: 0.3962 - accuracy: 0.8423 - val_loss: 0.3476 - val_accuracy: 0.8846
Epoch 48/100
241/241 [==============================] - 0s 25us/step - loss: 0.3945 - accuracy: 0.8423 - val_loss: 0.3436 - val_accuracy: 0.8846
Epoch 49/100
241/241 [==============================] - 0s 25us/step - loss: 0.3944 - accuracy: 0.8465 - val_loss: 0.3424 - val_accuracy: 0.8846
Epoch 50/100
241/241 [==============================] - 0s 25us/step - loss: 0.3945 - accuracy: 0.8465 - val_loss: 0.3401 - val_accuracy: 0.8846
Epoch 51/100
241/241 [==============================] - 0s 25us/step - loss: 0.3939 - accuracy: 0.8465 - val_loss: 0.3436 - val_accuracy: 0.8846
Epoch 52/100
241/241 [==============================] - 0s 25us/step - loss: 0.3938 - accuracy: 0.8423 - val_loss: 0.3513 - val_accuracy: 0.8846
Epoch 53/100
241/241 [==============================] - 0s 29us/step - loss: 0.3936 - accuracy: 0.8423 - val_loss: 0.3511 - val_accuracy: 0.8846
Epoch 54/100
241/241 [==============================] - 0s 29us/step - loss: 0.3933 - accuracy: 0.8423 - val_loss: 0.3448 - val_accuracy: 0.8846
Epoch 55/100
241/241 [==============================] - 0s 25us/step - loss: 0.3932 - accuracy: 0.8465 - val_loss: 0.3428 - val_accuracy: 0.8846
Epoch 56/100
241/241 [==============================] - 0s 25us/step - loss: 0.3927 - accuracy: 0.8465 - val_loss: 0.3424 - val_accuracy: 0.8846
Epoch 57/100
241/241 [==============================] - 0s 25us/step - loss: 0.3919 - accuracy: 0.8423 - val_loss: 0.3461 - val_accuracy: 0.8846
Epoch 58/100
241/241 [==============================] - 0s 29us/step - loss: 0.3917 - accuracy: 0.8423 - val_loss: 0.3461 - val_accuracy: 0.8846
Epoch 59/100
241/241 [==============================] - 0s 29us/step - loss: 0.3917 - accuracy: 0.8423 - val_loss: 0.3442 - val_accuracy: 0.8846
Epoch 60/100
241/241 [==============================] - 0s 29us/step - loss: 0.3917 - accuracy: 0.8423 - val_loss: 0.3495 - val_accuracy: 0.8846
Epoch 61/100
241/241 [==============================] - 0s 29us/step - loss: 0.3913 - accuracy: 0.8423 - val_loss: 0.3507 - val_accuracy: 0.8846
Epoch 62/100
241/241 [==============================] - 0s 25us/step - loss: 0.3906 - accuracy: 0.8423 - val_loss: 0.3463 - val_accuracy: 0.8846
Epoch 63/100
241/241 [==============================] - 0s 29us/step - loss: 0.3904 - accuracy: 0.8423 - val_loss: 0.3408 - val_accuracy: 0.8846
Epoch 64/100
241/241 [==============================] - 0s 25us/step - loss: 0.3910 - accuracy: 0.8465 - val_loss: 0.3398 - val_accuracy: 0.8846
Epoch 65/100
241/241 [==============================] - 0s 25us/step - loss: 0.3914 - accuracy: 0.8423 - val_loss: 0.3481 - val_accuracy: 0.8846
Epoch 66/100
241/241 [==============================] - 0s 29us/step - loss: 0.3895 - accuracy: 0.8423 - val_loss: 0.3449 - val_accuracy: 0.8846
Epoch 67/100
241/241 [==============================] - 0s 25us/step - loss: 0.3895 - accuracy: 0.8423 - val_loss: 0.3419 - val_accuracy: 0.8846
Epoch 68/100
241/241 [==============================] - 0s 25us/step - loss: 0.3889 - accuracy: 0.8423 - val_loss: 0.3416 - val_accuracy: 0.8846
Epoch 69/100
241/241 [==============================] - 0s 25us/step - loss: 0.3890 - accuracy: 0.8423 - val_loss: 0.3417 - val_accuracy: 0.8846
Epoch 70/100
241/241 [==============================] - 0s 25us/step - loss: 0.3896 - accuracy: 0.8423 - val_loss: 0.3410 - val_accuracy: 0.8846
Epoch 71/100
241/241 [==============================] - 0s 25us/step - loss: 0.3887 - accuracy: 0.8423 - val_loss: 0.3403 - val_accuracy: 0.8846
Epoch 72/100
241/241 [==============================] - 0s 25us/step - loss: 0.3881 - accuracy: 0.8423 - val_loss: 0.3436 - val_accuracy: 0.8846
Epoch 73/100
241/241 [==============================] - 0s 29us/step - loss: 0.3883 - accuracy: 0.8423 - val_loss: 0.3453 - val_accuracy: 0.8846
Epoch 74/100
241/241 [==============================] - 0s 29us/step - loss: 0.3880 - accuracy: 0.8423 - val_loss: 0.3406 - val_accuracy: 0.8846
Epoch 75/100
241/241 [==============================] - 0s 29us/step - loss: 0.3873 - accuracy: 0.8423 - val_loss: 0.3424 - val_accuracy: 0.8846
Epoch 76/100
241/241 [==============================] - 0s 29us/step - loss: 0.3869 - accuracy: 0.8423 - val_loss: 0.3460 - val_accuracy: 0.8846
Epoch 77/100
241/241 [==============================] - 0s 29us/step - loss: 0.3877 - accuracy: 0.8423 - val_loss: 0.3497 - val_accuracy: 0.8750
Epoch 78/100
241/241 [==============================] - 0s 25us/step - loss: 0.3870 - accuracy: 0.8423 - val_loss: 0.3448 - val_accuracy: 0.8846
Epoch 79/100
241/241 [==============================] - 0s 25us/step - loss: 0.3868 - accuracy: 0.8423 - val_loss: 0.3401 - val_accuracy: 0.8846
Epoch 80/100
241/241 [==============================] - 0s 25us/step - loss: 0.3862 - accuracy: 0.8423 - val_loss: 0.3421 - val_accuracy: 0.8846
Epoch 81/100
241/241 [==============================] - 0s 29us/step - loss: 0.3863 - accuracy: 0.8423 - val_loss: 0.3425 - val_accuracy: 0.8846
Epoch 82/100
241/241 [==============================] - 0s 25us/step - loss: 0.3860 - accuracy: 0.8423 - val_loss: 0.3383 - val_accuracy: 0.8846
Epoch 83/100
241/241 [==============================] - 0s 25us/step - loss: 0.3857 - accuracy: 0.8423 - val_loss: 0.3393 - val_accuracy: 0.8846
Epoch 84/100
241/241 [==============================] - 0s 25us/step - loss: 0.3855 - accuracy: 0.8423 - val_loss: 0.3385 - val_accuracy: 0.8846
Epoch 85/100
241/241 [==============================] - 0s 25us/step - loss: 0.3853 - accuracy: 0.8423 - val_loss: 0.3382 - val_accuracy: 0.8846
Epoch 86/100
241/241 [==============================] - 0s 25us/step - loss: 0.3851 - accuracy: 0.8423 - val_loss: 0.3406 - val_accuracy: 0.8846
Epoch 87/100
241/241 [==============================] - 0s 25us/step - loss: 0.3849 - accuracy: 0.8423 - val_loss: 0.3408 - val_accuracy: 0.8846
Epoch 88/100
241/241 [==============================] - 0s 25us/step - loss: 0.3848 - accuracy: 0.8423 - val_loss: 0.3423 - val_accuracy: 0.8846
Epoch 89/100
241/241 [==============================] - 0s 29us/step - loss: 0.3848 - accuracy: 0.8423 - val_loss: 0.3416 - val_accuracy: 0.8846
Epoch 90/100
241/241 [==============================] - 0s 25us/step - loss: 0.3849 - accuracy: 0.8423 - val_loss: 0.3454 - val_accuracy: 0.8846
Epoch 91/100
241/241 [==============================] - 0s 25us/step - loss: 0.3855 - accuracy: 0.8423 - val_loss: 0.3498 - val_accuracy: 0.8750
Epoch 92/100
241/241 [==============================] - 0s 25us/step - loss: 0.3837 - accuracy: 0.8423 - val_loss: 0.3397 - val_accuracy: 0.8846
Epoch 93/100
241/241 [==============================] - 0s 25us/step - loss: 0.3839 - accuracy: 0.8423 - val_loss: 0.3347 - val_accuracy: 0.8846
Epoch 94/100
241/241 [==============================] - 0s 25us/step - loss: 0.3846 - accuracy: 0.8423 - val_loss: 0.3377 - val_accuracy: 0.8846
Epoch 95/100
241/241 [==============================] - 0s 25us/step - loss: 0.3839 - accuracy: 0.8423 - val_loss: 0.3349 - val_accuracy: 0.8846
Epoch 96/100
241/241 [==============================] - 0s 21us/step - loss: 0.3834 - accuracy: 0.8423 - val_loss: 0.3374 - val_accuracy: 0.8846
Epoch 97/100
241/241 [==============================] - 0s 29us/step - loss: 0.3834 - accuracy: 0.8423 - val_loss: 0.3432 - val_accuracy: 0.8846
Epoch 98/100
241/241 [==============================] - 0s 29us/step - loss: 0.3835 - accuracy: 0.8423 - val_loss: 0.3428 - val_accuracy: 0.8846
Epoch 99/100
241/241 [==============================] - 0s 29us/step - loss: 0.3825 - accuracy: 0.8423 - val_loss: 0.3402 - val_accuracy: 0.8846
Epoch 100/100
241/241 [==============================] - 0s 25us/step - loss: 0.3826 - accuracy: 0.8423 - val_loss: 0.3392 - val_accuracy: 0.8846

0.11538461538461542